### ISSUE TITLE
Extensions Settings unavailable on Beta 8.1

### ISSUE THREAD

**Issue by AvianAeternum** [flagrow/mail-drivers#2]
After a successful install of the extension, and enabling it, the settings ellipsis to configure it is not available. 
Flarum
0.1.0-beta.8.1

PHP
7.2.15-0ubuntu0.18.04.2

MySQL
5.7.25-0ubuntu0.18.04.2

**Comment by luceos** [comment]
It's not compatible with beta 8.

**Comment by AvianAeternum** [comment]
Alright.
